export { default as GeneralSettings } from './GeneralSettings'
export { default as OtherSettings } from './OtherSettings'
export { default as Tools } from './Tools'
export { default as WineSettings } from './WineSettings'
export { default as WineExtensions } from './WineExtensions'
export { default as AdvancedSettings } from './AdvancedSettings'
export { default as SyncSaves } from './SyncSaves'
