image: Visual Studio 2019

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - npm install -g pnpm@10
  - pnpm install
  - pnpm download-helper-binaries
  - ps: Install-Module -Name SignPath -Force -Scope CurrentUser

environment:
  GH_TOKEN:
    secure: kZMGyhBmfPsJKEryrd+I7gTEudm8tW0jSrKKhtT/3fbqKQzndTWp47C1Eetx5kFs
  SIGNPATH_API_TOKEN:
    secure: havQJWi4z2xX9aYI2szN9f89BROoFFzFQCELaBflr3ZOjJXq2P/xNsmgYbJtJoWw

build_script:
  - npm run release:win
  - 7z.exe a -tzip dist\HeroicWin.zip dist\*x64.exe dist\*arm64.exe dist\*.blockmap dist\*.yml

test: off

artifacts:
  - path: dist\HeroicWin.zip
    name: Heroic_Windows_Files
