patchedDependencies:
  '@types/node@22.15.18': patches/@types__node@22.15.18.patch
  howlongtobeat-js@1.0.2: patches/howlongtobeat-js@1.0.2.patch

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@swc/core'
  - electron
  - esbuild
  - register-scheme
  - unrs-resolver

overrides:
  ts-morph: 17.0.1
  got@<11.8.5: '>=11.8.5'
  cross-spawn@<6.0.6: '>=6.0.6'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  electron@<28.3.2: '>=28.3.2'
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  electron@<35.7.5: '>=35.7.5'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
  playwright@<1.55.1: '>=1.55.1'
  tmp@<=0.2.3: '>=0.2.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
