export { default as GeneralSettings } from './GeneralSettings'
export { default as GamesSettings } from './GamesSettings'
export { default as AdvancedSettings } from './AdvancedSettings'
export { default as SyncSaves } from './SyncSaves'
export { default as SystemInfo } from './SystemInfo'
