name: 'Prerequisite setup'
description: 'Installs dependencies (Node itself, node_modules, node-gyp, helper binaries)'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        standalone: ${{ runner.os == 'Windows' }}
    - uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
    - name: Install node-gyp
      run: pnpm add --global node-gyp
      shell: bash
    - name: Install modules
      run: pnpm install
      shell: bash
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
    - name: Download helper binaries
      run: pnpm download-helper-binaries
      shell: bash
