// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: src/backend/storeManagers/steam/steammessages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CMsgClientLicenseList {
  eresult?: number | undefined;
  licenses: CMsgClientLicenseList_License[];
}

export interface CMsgClientLicenseList_License {
  packageId?: number | undefined;
  timeCreated?: number | undefined;
  timeNextProcess?: number | undefined;
  minuteLimit?: number | undefined;
  minutesUsed?: number | undefined;
  paymentMethod?: number | undefined;
  flags?: number | undefined;
  purchaseCountryCode?: string | undefined;
  licenseType?: number | undefined;
  territoryCode?: number | undefined;
  changeNumber?: number | undefined;
  ownerId?: number | undefined;
  initialPeriod?: number | undefined;
  initialTimeUnit?: number | undefined;
  renewalPeriod?: number | undefined;
  renewalTimeUnit?: number | undefined;
  accessToken?: bigint | undefined;
  masterPackageId?: number | undefined;
}

function createBaseCMsgClientLicenseList(): CMsgClientLicenseList {
  return { eresult: 2, licenses: [] };
}

export const CMsgClientLicenseList: MessageFns<CMsgClientLicenseList> = {
  encode(message: CMsgClientLicenseList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eresult !== undefined && message.eresult !== 2) {
      writer.uint32(8).int32(message.eresult);
    }
    for (const v of message.licenses) {
      CMsgClientLicenseList_License.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgClientLicenseList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgClientLicenseList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.eresult = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.licenses.push(CMsgClientLicenseList_License.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgClientLicenseList {
    return {
      eresult: isSet(object.eresult) ? globalThis.Number(object.eresult) : 2,
      licenses: globalThis.Array.isArray(object?.licenses)
        ? object.licenses.map((e: any) => CMsgClientLicenseList_License.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CMsgClientLicenseList): unknown {
    const obj: any = {};
    if (message.eresult !== undefined && message.eresult !== 2) {
      obj.eresult = Math.round(message.eresult);
    }
    if (message.licenses?.length) {
      obj.licenses = message.licenses.map((e) => CMsgClientLicenseList_License.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgClientLicenseList>, I>>(base?: I): CMsgClientLicenseList {
    return CMsgClientLicenseList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgClientLicenseList>, I>>(object: I): CMsgClientLicenseList {
    const message = createBaseCMsgClientLicenseList();
    message.eresult = object.eresult ?? 2;
    message.licenses = object.licenses?.map((e) => CMsgClientLicenseList_License.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCMsgClientLicenseList_License(): CMsgClientLicenseList_License {
  return {
    packageId: 0,
    timeCreated: 0,
    timeNextProcess: 0,
    minuteLimit: 0,
    minutesUsed: 0,
    paymentMethod: 0,
    flags: 0,
    purchaseCountryCode: "",
    licenseType: 0,
    territoryCode: 0,
    changeNumber: 0,
    ownerId: 0,
    initialPeriod: 0,
    initialTimeUnit: 0,
    renewalPeriod: 0,
    renewalTimeUnit: 0,
    accessToken: BigInt("0"),
    masterPackageId: 0,
  };
}

export const CMsgClientLicenseList_License: MessageFns<CMsgClientLicenseList_License> = {
  encode(message: CMsgClientLicenseList_License, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packageId !== undefined && message.packageId !== 0) {
      writer.uint32(8).uint32(message.packageId);
    }
    if (message.timeCreated !== undefined && message.timeCreated !== 0) {
      writer.uint32(21).fixed32(message.timeCreated);
    }
    if (message.timeNextProcess !== undefined && message.timeNextProcess !== 0) {
      writer.uint32(29).fixed32(message.timeNextProcess);
    }
    if (message.minuteLimit !== undefined && message.minuteLimit !== 0) {
      writer.uint32(32).int32(message.minuteLimit);
    }
    if (message.minutesUsed !== undefined && message.minutesUsed !== 0) {
      writer.uint32(40).int32(message.minutesUsed);
    }
    if (message.paymentMethod !== undefined && message.paymentMethod !== 0) {
      writer.uint32(48).uint32(message.paymentMethod);
    }
    if (message.flags !== undefined && message.flags !== 0) {
      writer.uint32(56).uint32(message.flags);
    }
    if (message.purchaseCountryCode !== undefined && message.purchaseCountryCode !== "") {
      writer.uint32(66).string(message.purchaseCountryCode);
    }
    if (message.licenseType !== undefined && message.licenseType !== 0) {
      writer.uint32(72).uint32(message.licenseType);
    }
    if (message.territoryCode !== undefined && message.territoryCode !== 0) {
      writer.uint32(80).int32(message.territoryCode);
    }
    if (message.changeNumber !== undefined && message.changeNumber !== 0) {
      writer.uint32(88).int32(message.changeNumber);
    }
    if (message.ownerId !== undefined && message.ownerId !== 0) {
      writer.uint32(96).uint32(message.ownerId);
    }
    if (message.initialPeriod !== undefined && message.initialPeriod !== 0) {
      writer.uint32(104).uint32(message.initialPeriod);
    }
    if (message.initialTimeUnit !== undefined && message.initialTimeUnit !== 0) {
      writer.uint32(112).uint32(message.initialTimeUnit);
    }
    if (message.renewalPeriod !== undefined && message.renewalPeriod !== 0) {
      writer.uint32(120).uint32(message.renewalPeriod);
    }
    if (message.renewalTimeUnit !== undefined && message.renewalTimeUnit !== 0) {
      writer.uint32(128).uint32(message.renewalTimeUnit);
    }
    if (message.accessToken !== undefined && message.accessToken !== BigInt("0")) {
      if (BigInt.asUintN(64, message.accessToken) !== message.accessToken) {
        throw new globalThis.Error("value provided for field message.accessToken of type uint64 too large");
      }
      writer.uint32(136).uint64(message.accessToken);
    }
    if (message.masterPackageId !== undefined && message.masterPackageId !== 0) {
      writer.uint32(144).uint32(message.masterPackageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CMsgClientLicenseList_License {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCMsgClientLicenseList_License();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.packageId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.timeCreated = reader.fixed32();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.timeNextProcess = reader.fixed32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minuteLimit = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.minutesUsed = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.paymentMethod = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.flags = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.purchaseCountryCode = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.licenseType = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.territoryCode = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.changeNumber = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.ownerId = reader.uint32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.initialPeriod = reader.uint32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.initialTimeUnit = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.renewalPeriod = reader.uint32();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.renewalTimeUnit = reader.uint32();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.accessToken = reader.uint64() as bigint;
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.masterPackageId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CMsgClientLicenseList_License {
    return {
      packageId: isSet(object.packageId) ? globalThis.Number(object.packageId) : 0,
      timeCreated: isSet(object.timeCreated) ? globalThis.Number(object.timeCreated) : 0,
      timeNextProcess: isSet(object.timeNextProcess) ? globalThis.Number(object.timeNextProcess) : 0,
      minuteLimit: isSet(object.minuteLimit) ? globalThis.Number(object.minuteLimit) : 0,
      minutesUsed: isSet(object.minutesUsed) ? globalThis.Number(object.minutesUsed) : 0,
      paymentMethod: isSet(object.paymentMethod) ? globalThis.Number(object.paymentMethod) : 0,
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : 0,
      purchaseCountryCode: isSet(object.purchaseCountryCode) ? globalThis.String(object.purchaseCountryCode) : "",
      licenseType: isSet(object.licenseType) ? globalThis.Number(object.licenseType) : 0,
      territoryCode: isSet(object.territoryCode) ? globalThis.Number(object.territoryCode) : 0,
      changeNumber: isSet(object.changeNumber) ? globalThis.Number(object.changeNumber) : 0,
      ownerId: isSet(object.ownerId) ? globalThis.Number(object.ownerId) : 0,
      initialPeriod: isSet(object.initialPeriod) ? globalThis.Number(object.initialPeriod) : 0,
      initialTimeUnit: isSet(object.initialTimeUnit) ? globalThis.Number(object.initialTimeUnit) : 0,
      renewalPeriod: isSet(object.renewalPeriod) ? globalThis.Number(object.renewalPeriod) : 0,
      renewalTimeUnit: isSet(object.renewalTimeUnit) ? globalThis.Number(object.renewalTimeUnit) : 0,
      accessToken: isSet(object.accessToken) ? BigInt(object.accessToken) : BigInt("0"),
      masterPackageId: isSet(object.masterPackageId) ? globalThis.Number(object.masterPackageId) : 0,
    };
  },

  toJSON(message: CMsgClientLicenseList_License): unknown {
    const obj: any = {};
    if (message.packageId !== undefined && message.packageId !== 0) {
      obj.packageId = Math.round(message.packageId);
    }
    if (message.timeCreated !== undefined && message.timeCreated !== 0) {
      obj.timeCreated = Math.round(message.timeCreated);
    }
    if (message.timeNextProcess !== undefined && message.timeNextProcess !== 0) {
      obj.timeNextProcess = Math.round(message.timeNextProcess);
    }
    if (message.minuteLimit !== undefined && message.minuteLimit !== 0) {
      obj.minuteLimit = Math.round(message.minuteLimit);
    }
    if (message.minutesUsed !== undefined && message.minutesUsed !== 0) {
      obj.minutesUsed = Math.round(message.minutesUsed);
    }
    if (message.paymentMethod !== undefined && message.paymentMethod !== 0) {
      obj.paymentMethod = Math.round(message.paymentMethod);
    }
    if (message.flags !== undefined && message.flags !== 0) {
      obj.flags = Math.round(message.flags);
    }
    if (message.purchaseCountryCode !== undefined && message.purchaseCountryCode !== "") {
      obj.purchaseCountryCode = message.purchaseCountryCode;
    }
    if (message.licenseType !== undefined && message.licenseType !== 0) {
      obj.licenseType = Math.round(message.licenseType);
    }
    if (message.territoryCode !== undefined && message.territoryCode !== 0) {
      obj.territoryCode = Math.round(message.territoryCode);
    }
    if (message.changeNumber !== undefined && message.changeNumber !== 0) {
      obj.changeNumber = Math.round(message.changeNumber);
    }
    if (message.ownerId !== undefined && message.ownerId !== 0) {
      obj.ownerId = Math.round(message.ownerId);
    }
    if (message.initialPeriod !== undefined && message.initialPeriod !== 0) {
      obj.initialPeriod = Math.round(message.initialPeriod);
    }
    if (message.initialTimeUnit !== undefined && message.initialTimeUnit !== 0) {
      obj.initialTimeUnit = Math.round(message.initialTimeUnit);
    }
    if (message.renewalPeriod !== undefined && message.renewalPeriod !== 0) {
      obj.renewalPeriod = Math.round(message.renewalPeriod);
    }
    if (message.renewalTimeUnit !== undefined && message.renewalTimeUnit !== 0) {
      obj.renewalTimeUnit = Math.round(message.renewalTimeUnit);
    }
    if (message.accessToken !== undefined && message.accessToken !== BigInt("0")) {
      obj.accessToken = message.accessToken.toString();
    }
    if (message.masterPackageId !== undefined && message.masterPackageId !== 0) {
      obj.masterPackageId = Math.round(message.masterPackageId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CMsgClientLicenseList_License>, I>>(base?: I): CMsgClientLicenseList_License {
    return CMsgClientLicenseList_License.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CMsgClientLicenseList_License>, I>>(
    object: I,
  ): CMsgClientLicenseList_License {
    const message = createBaseCMsgClientLicenseList_License();
    message.packageId = object.packageId ?? 0;
    message.timeCreated = object.timeCreated ?? 0;
    message.timeNextProcess = object.timeNextProcess ?? 0;
    message.minuteLimit = object.minuteLimit ?? 0;
    message.minutesUsed = object.minutesUsed ?? 0;
    message.paymentMethod = object.paymentMethod ?? 0;
    message.flags = object.flags ?? 0;
    message.purchaseCountryCode = object.purchaseCountryCode ?? "";
    message.licenseType = object.licenseType ?? 0;
    message.territoryCode = object.territoryCode ?? 0;
    message.changeNumber = object.changeNumber ?? 0;
    message.ownerId = object.ownerId ?? 0;
    message.initialPeriod = object.initialPeriod ?? 0;
    message.initialTimeUnit = object.initialTimeUnit ?? 0;
    message.renewalPeriod = object.renewalPeriod ?? 0;
    message.renewalTimeUnit = object.renewalTimeUnit ?? 0;
    message.accessToken = object.accessToken ?? BigInt("0");
    message.masterPackageId = object.masterPackageId ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
