name: heroic
title: Heroic Games Launcher
summary: An Open Source Launcher for GOG, Epic Games and Amazon Games
description: |
  Heroic is an Open Source Games Launcher. Right now it supports launching games from the Epic Games
  Store using Legendary, Amazon Games using Nile and GOG Games using our custom implementations Nile and gogdl.
adopt-info: heroic-app
icon: src/frontend/assets/heroic-icon.svg
grade: stable
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
base: core24
compression: lzo
assumes:
  - snapd2.62

license: GPL-3.0-only
contact: https://discord.gg/rHJ2uqdquK
issues: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues
donation:
  - https://github.com/sponsors/Heroic-Games-Launcher
  - https://patreon.com/heroicgameslauncher
  - https://ko-fi.com/heroicgames
source-code: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
website: https://heroicgameslauncher.com/

apps:
  heroic:
    command-chain: [snap/command-chain/desktop-launch-heroic]
    command: opt/Heroic/heroic --no-sandbox
    desktop: usr/share/applications/heroic.desktop
    common-id: com.heroicgameslauncher.hgl
    environment:
      HOME: $SNAP_USER_COMMON
      PATH: $SNAP/usr/games:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/i386-linux-gnu:$SNAP/usr/lib/i386-linux-gnu/pulseaudio:$LD_LIBRARY_PATH
    extensions: [gnome]
    plugs:
      - audio-playback
      - unity7
      - network
      - network-bind
      - screen-inhibit-control
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2
      - system-backup

plugs:
  shared-memory:
    private: true

layout:
  /usr/lib/x86_64-linux-gnu/mangohud:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/mangohud

lint:
  # Snapcraft's `ldd` lint can't handle 32-bit things,
  # So just make it quiet and also make builds a surprising amount faster
  ignore:
    - library:
        - lib/i386-linux-gnu/**
        - usr/lib/i386-linux-gnu/**
        - lib32/**
        - usr/lib32/**
        - opt/wine-stable/lib/wine/i386-unix/**

package-repositories:
  - type: apt
    url: https://dl.winehq.org/wine-builds/ubuntu
    suites: [noble]
    components: [main]
    architectures: [amd64, i386]
    key-id: D43F640145369C51D786DDEA76F1A20FF987672F

parts:
  heroic-app:
    plugin: nil
    build-packages: [wget, curl]
    override-build: |
      if [ "$CRAFT_ARCH_TRIPLET_BUILD_FOR" = "x86_64-linux-gnu" ]; then
        URL=$(curl -s "https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest" | grep -o 'https.*linux-amd64\.deb' | head -1)
        wget "$URL"
      elif [ "$CRAFT_ARCH_TRIPLET_BUILD_FOR" = "aarch64-linux-gnu" ]; then
        URL=$(curl -s "https://api.github.com/repos/Heroic-Games-Launcher/HeroicGamesLauncher/releases/latest" | grep -o 'https.*linux-arm64\.deb' | head -1)
        wget "$URL"
      fi

      DEB_FILE=$(basename "$URL")
      dpkg-deb -x "$DEB_FILE" "$CRAFT_PART_INSTALL"
      sed -i 's|Name=Heroic Games Launcher|Name=Heroic [Snap]|' $CRAFT_PART_INSTALL/usr/share/applications/heroic.desktop
      VERSION=$(echo "$DEB_FILE" | sed -n 's/Heroic-\([0-9.]*\)-.*/\1/p')
      craftctl set version="$VERSION"
    prime:
      - opt/Heroic
      - usr/share/applications/heroic.desktop

  base-dependencies:
    after: [heroic-app]
    plugin: nil
    stage-packages: [curl, zenity, unzip, cabextract, 7zip, xz-utils]

  gamemode:
    plugin: nil
    stage-packages: [gamemode, gamemode-daemon, libgamemode0, libgamemodeauto0]
    prime:
      - etc/security/limits.d/10-gamemode.conf
      - usr/bin/gamemoded
      - usr/games/gamemodelist
      - usr/games/gamemoderun
      - usr/games/gamemode-simulate-game
      - usr/lib/*/libgamemode.so*
      - usr/lib/*/libgamemodeauto.so*
      - usr/lib/*/libinih.so*
      - usr/lib/systemd/user/gamemoded.service
      - usr/lib/sysusers.d/gamemode.conf
      - usr/libexec/cpucorectl
      - usr/libexec/cpugovctl
      - usr/libexec/gpuclockctl
      - usr/libexec/procsysctl
      - usr/share/dbus-1/services/com.feralinteractive.GameMode.service
      - usr/share/gamemode/gamemode.ini
      - usr/share/lintian/overrides/libgamemode0
      - usr/share/metainfo/io.github.feralinteractive.gamemode.metainfo.xml
      - usr/share/polkit-1/actions/com.feralinteractive.GameMode.policy
      - usr/share/polkit-1/rules.d/gamemode.rules

  mangohud:
    plugin: nil
    stage-packages: [mangohud, libspdlog1.12, libfmt9]
    prime:
      - usr/bin/mangohud
      - usr/lib/x86_64-linux-gnu/mangohud/libMangoHud.so*
      - usr/lib/x86_64-linux-gnu/mangohud/libMangoHud_opengl.so*
      - usr/lib/x86_64-linux-gnu/mangohud/libMangoHud_shim.so*
      - usr/lib/x86_64-linux-gnu/libspdlog.so*
      - usr/lib/x86_64-linux-gnu/libfmt.so*
      - usr/share/metainfo/io.github.flightlessmango.mangohud.metainfo.xml
      - usr/share/vulkan/implicit_layer.d/MangoHud.x86_64.json

  winehq-stable:
    plugin: nil
    stage-packages:
      - winehq-stable
    prime:
      - -opt
      - -usr/bin/wine*

  command-chain:
    plugin: dump
    source: ./snap/command-chain/
    organize:
      desktop-launch-heroic: snap/command-chain/desktop-launch-heroic

  cleanup:
    after: [heroic-app, base-dependencies, gamemode, mangohud, winehq-stable]
    plugin: nil
    build-snaps:
      - mesa-2404
      - gnome-46-2404
    override-prime: |
      set -eux
      cd /snap/mesa-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/mesa-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;

      cd /snap/gnome-46-2404/current/usr/lib
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/{} \;
      cd /snap/gnome-46-2404/current/usr/share
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/share/{} \;
