name: Code check
permissions:
  contents: read

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: ./.github/actions/install-deps
      - name: Check Typescript syntax
        run: pnpm codecheck
