name: Update AUR
permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  update-aur:
    runs-on: ubuntu-latest

    container:
      image: archlinux

    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm nodejs-lts-krypton
      - uses: actions/checkout@v6
      - name: Update PKGBUILD
        run: node meta/createAurPkgbuild.mts
        id: script
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.3
        with:
          pkgname: heroic-games-launcher-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE }}
          commit_message: Update to ${{ steps.script.outputs.pkgver }}-${{ steps.script.outputs.pkgrel }}
          ssh_keyscan_types: rsa,ecdsa,ed25519
          updpkgsums: true
